# Generated by Django 4.2.5 on 2023-09-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Community',
        ),
    ]
